name: mlpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.*
  - conda
  - xgboost
  - jupyterlab
  - pandas>=2.0
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - upsetplot
  # Website Rendering/building
  - mkdocs
  - pygments
  - mkdocs-material
  - mkdocs-material-extensions
  - pymdown-extensions
  - pip
  - pip:
    - mknotebooks
    - mkdocs-minify-plugin

