site_name: Introduction to Machine learning in Python
site_description: >-
  lessons for introduction to machine learning in Python course: Exploratory Data Analysis, Regression,
site_author: Sydney Informatics Hub Team
copyright: Copyright &copy; 2020 - 2025 Sydney Informatics Hub, The University of Sydney - all right reserved


theme:
  # name: mkdocs
  name: material
  features:
    - navigation.instant
    # - navigation.tabs

docs_dir: course
site_dir: docs
dev_addr: localhost:8001

extra_css:
  - theme/css/extra.css
  # - theme/css/lesson.css

nav:
  - Home: index.md
  - Session 1:
      - Exploratory Data Analysis: notebooks/03-EDA.ipynb
      - Linear Regression: notebooks/10-LinReg.ipynb

plugins:
  # - mkdocs-jupyter:
      # execute: True
      # include_source: True
    - mknotebooks:
        execute: False
        # enable_default_pandas_dataframe_styling: false
        # enable_default_jupyter_cell_styling: false
        # allow_errors: true
        # write_markdown: true

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - smarty
