site_name: Introduction to Machine learning in Python
site_description: >-
  lessons for introduction to machine learning in Python course: Exploratory Data Analysis, Regression,
site_author: Sydney Informatics Hub Team
copyright: >-
  Copyright &copy; 2020 - 2025 Sydney Informatics Hub, The University of Sydney – all rights reserved – 
  <a href="#__consent">Change cookie settings</a>


theme:
  name: material
  font:
    text: Source Sans Pro
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy

docs_dir: course
site_dir: docs
dev_addr: localhost:8001

extra_css:
  - theme/css/extra.css

extra_javascript:
  # Needed for mathjax support
  - theme/js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Extra custom js code
  - theme/js/extra.js

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
  consent:
    title: Cookie consent
    description: >-
      We use cookies to analyse our website traffic and to understand where our 
      visitors are coming from. <a href="https://www.sydney.edu.au/privacy-statement.html">Privacy Policy</a>
    actions:
      - accept
      - reject
      - manage

nav:
  - index.md
  - Setup: setup.md
  - Overview: 01-ML1.md
  - Session 1 - Regression:
      - Exploratory Data Analysis: notebooks/03-EDA.ipynb
      - Linear Regression: notebooks/10-LinReg.ipynb
      - Advanced Regression: notebooks/11-RidgeLassoElasticNet.ipynb
      - Random Forest and K-Nearest Neighbours: notebooks/30-RF_knn.ipynb
      - GBM and XGBoost: notebooks/45-Xgboost.ipynb
  - Session 2 - Classification:
      - Classification: notebooks/50-Classification.ipynb
      - Unsupervised Learning: notebooks/90-Unsupervised.ipynb

plugins:
  - mknotebooks:
      execute: False
      # enable_default_pandas_dataframe_styling: false
      # enable_default_jupyter_cell_styling: false
      # allow_errors: true
      # write_markdown: true
      # Hide some code cells using cell tags
      tag_remove_configs:
        remove_cell_tags:
          - hide
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
      minify_js: true
      js_files:
        - theme/js/config.js

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - smarty
  - pymdownx.arithmatex:
      generic: true
