name: mlpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - conda
  - anaconda
  - xgboost
  - jupyterlab>=3
  - jupyterlab-git>=0.30.1
  - ipympl
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - sklearn-contrib-py-earth
  - upsetplot
  # Website Rendering/building
  - pip
  - pip:
    - mknotebooks
    - mkdocs>=1.2
    - mkdocs-material>=7.1.7
    - mkdocs-material-extensions>=1.0.1
    - mkdocs-minify-plugin
    - pymdown-extensions>=8.2

