name: mlpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - conda
  - anaconda
  - xgboost
  - jupyterlab>=3
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - sklearn-contrib-py-earth
  - upsetplot
  # Website Rendering/building
  - mkdocs=1.2
  - mkdocs-material=7.1.7
  - mkdocs-material-extensions=1.0.1
  - pymdown-extensions=8.2
  - pip
  - pip:
    - mknotebooks
    - mkdocs-minify-plugin

